version: '3.7'
services:
  istsos-db:
    # build:
    #  context: ./db/
    #  dockerfile: Dockerfile
    image: postgis/postgis:12-2.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: istsos
    # POSTGRES_HOST: istsos_istsos-db_1
      TZ: Europe/Zurich
    volumes:
      - v-istsos-pgdata:/var/lib/postgresql/data
  istsos:
    # build: 
    #  context: ./
    #  dockerfile: Dockerfile
    image: istsos/istsos:2.4.0-RC4
    restart: always
    ports:
      - 80:80
    volumes:
      - v-istsos-services:/usr/share/istsos/services
volumes:
  v-istsos-pgdata:
  v-istsos-services:
